/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hopital;

/*
Bibliotheque extern
*/
import mdlaf.*;
import mdlaf.animation.*;
import javax.swing.*;
import java.awt.*;
import mdlaf.utils.MaterialColors;

/**
 *
 * @author najibboubrim
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(170, 100, 250, 20);

        jSeparator2.setForeground(new java.awt.Color(221, 221, 221));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(240, 690, 80, 20);

        jLabel5.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText(" J'ai déja un compte");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 700, 120, 20);

        jLabel2.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INSCRIPTION DES EMPLOYÉES");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 40, 360, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/testtt.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 155);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/icons8-doctor.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 170, 80, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hopital/icons8-doctor_female.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 170, 90, 100);

        jLabel6.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel6.setText("Nom d'utilisateur");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 500, 120, 16);

        jLabel7.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel7.setText("Mot de passe");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 570, 100, 16);

        jLabel8.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel8.setText("Nom");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 300, 28, 16);

        jLabel9.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel9.setText("Prénom");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(340, 300, 45, 16);

        jLabel10.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel10.setText("Date de naissance");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 370, 110, 16);

        jLabel11.setFont(new java.awt.Font("Lato", 1, 13)); // NOI18N
        jLabel11.setText("Sexe");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 370, 28, 16);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel12.setText("Type d'emploi");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 440, 110, 15);

        jButton1.setText("Inscrire");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 660, 97, 29);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 320, 230, 40);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(330, 320, 230, 40);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 520, 230, 40);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(400, 400, 120, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Male");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(330, 400, 70, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choix d'emploi", "Docteur", "Labortoir", "Dentiste" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(30, 460, 230, 27);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Année", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(200, 400, 95, 27);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jour", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(30, 400, 80, 27);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mois", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Decembre" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(110, 400, 90, 27);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(30, 590, 230, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        MaterialUIMovement.add(jButton1, MaterialColors.TEAL_A100);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                try {
			UIManager.setLookAndFeel (new MaterialLookAndFeel ());
		}
		catch (UnsupportedLookAndFeelException e) {
			e.printStackTrace ();
		}
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
